### PR TITLE
Support for binary, barrier, notification, and door lock

### PR DESCRIPTION
**Pull request by dxdc**
@mjcumming I think there are some more changes needed to support all of the values, but this should be a start. Welcome any changes (or, let me know what I've done incorrectly and will make needed changes).

Barrier/binary/notification are read-only, but lock should be able to get triggered.

Have also made some minor edits to your install `README` based on my experience on RPI.

### CODE REVIEW

**Review by mjcumming — COMMENTED** [review]
Few thoughts/questions. I think we could move some of these devices to Homie4. Ie. lock.

Another would be to have keep sensors that have a binary state limited to as few devices as possible rather then enumerating a whole pile of similar device types. It would make device management on the controller side of things easier.

Thoughts?

**Comment by dxdc** [comment]
> Another would be to have keep sensors that have a binary state limited to as few devices as possible rather then enumerating a whole pile of similar device types. It would make device management on the controller side of things easier.

I'm open to either approach. I agree if there is just one output it probably doesn't make sense to create too many output classes. This is one of those cases though where the `uom` attribute would be ideal, since we could just specify which uom and it could be formatted automatically without necessarily creating separate class files.

I still haven't had a chance to test this in detail but hope to get to in the next few days.

**Comment by mjcumming** [comment]
I am hoping we can make some progress on common device implementations as being discussed [here](https://github.com/homieiot/convention/issues/152)

**Comment by mjcumming** [comment]
@dxdc if your testing went well I will merge. I would like to keep only one type of contact/notification/motion/sensor device rather than one for each type.

**Comment by dxdc** [comment]
@mjcumming thanks for the reminder! agree on a more common device implementation/standard. I haven't had time to test this but hope to get to it before the end of the week.

**Comment by dxdc** [comment]
@mjcumming It didn't work actually in testing, because I realized I needed to make changes to https://github.com/mjcumming/Homie4/tree/master/homie also to get this to work.

That being said, I was able to manage this a different way (using variables) which may be simpler long-term for this type of application. Feel free to use or delete the PR if you like! Thanks for your support and help reviewing this.

**Comment by mjcumming** [comment]
changes look good to me. thank you for the contribution

**Comment by dxdc** [comment]
@mjcumming OK -- thanks! But, it doesn't work because there are no associated devices in the homie repo.

**Comment by dxdc** [comment]
(It causes a failure on startup)

**Comment by mjcumming** [comment]
Ok, if possible can you change to using the existing contact device?

**Comment by dxdc** [comment]
Well, it would have to be done for all "new" device types that I added (barrier, notification, etc.). I am not pursuing this route anymore, have figured out a way to just achieve it using variables which is working quite well actually!

Anyway, seems you closed the PR so it won't be merged :) But, as I said, feel free to use some of the updates to the documentation for example.

Would definitely appreciate a new release of ISY-homie that uses the latest ISY994v5 too. Thanks @mjcumming

**Pull request closed without merging**
